### ISSUE TITLE
Wallet not sending Amonveo

### ISSUE THREAD

**Issue by 130880** [amoveo-project/js-web-wallet#1]
Hi , i have been trying to send out my Amoveo to my HitBTC account and it keeps coming up as the transaction has been successful however it never leaves my wallet and has not been received by HitBtc
please see below screen shot of blockchain confirmation:
![image](https://user-images.githubusercontent.com/51386100/58916932-a44e2500-8757-11e9-8774-db1c4af1c11f.png)
this my wallet details after transaction:
![image](https://user-images.githubusercontent.com/51386100/58916996-c9db2e80-8757-11e9-932e-cb0a0098cd6c.png)

i have tried doing this a few times just in case it was in error on my side but each time it states transaction complete but never goes through?
your help would be appreciated 

thank you

**Comment by vden** [comment]
Thanks for report.

That's a known issue, it's connected with the full node. Txid `ZXJyb3I+` you keep seeing is just `error` word in base64, which is returned by the node in case of any troubles with feeding transaction into mempool.

Anyway, we'll look into it as there were troubles with full nodes recently, so it would be possible fixed by another full node update. I'll update you once we check it.

**Comment by vden** [comment]
If you need to send money right now, you can use mobile wallet or original light node (http://139.59.144.76:8080/wallet.html for instance).

**Comment by 130880** [comment]
Hi denis
Thank you for getting back to me 
Will  try original wallet now but if it doesn’t work will use link you provided below
Thanks 

John Italiano
0438556662

**Comment by 130880** [comment]
Hi denis 
Have tried again the wallet and it’s still not working...
Do you have a step by step guide for using the original light node -  a Nubie at all this 🙄
Thanks 

John Italiano
0438556662

**Comment by 130880** [comment]
Hi denis
I found a set by step guide for the light node wallet but it to also wouldn’t let me transfer?
Very frustrating 
Are you able to assist in completing transfer?
Thanks

**Comment by vden** [comment]
@130880 sure, let me help you. I've contacted you in Telegram.

**Comment by filip1983** [comment]
Hi guys have same problem with my Amoveo wallet @vden can you help me pls im unable to send funds from my wallet

**Comment by vden** [comment]
@filip1983 hello and sorry for the late reply. 

Unfortunately, we were unable to reproduce the issue on myveowallet.com

Could you please try few more things:
1) Try different browser or at least hard reload (with cache clear) on myveowallet.com
2) Try original Zack's light node at http://159.89.87.58:8080/txs.html 
You can set `channel node IP` to 95.217.85.84 (that's the node myveowallet uses). Private key to use with that tool can be exported from myveowallet (gear icon menu at the top of the screen).

You can reach me at Telegram [t.me/denis_voskvitsov](https://t.me/denis_voskvitsov) if you have any questions on that.
